version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout
      # - node/install:
      #     node-version: "17.0.1"
      - node/install-packages:
          pkg-manager: npm
      - build:
          command: npm run build
      - run:
          command: npm run test
workflows:
  build-and-test:
    jobs:
      - build-and-test
